### ISSUE TITLE
Shapefile export type

### ISSUE THREAD

**Issue by fcujorick** [hotosm/osm-export-tool#281]
Hi guys, 

Since I know that Mapzen is stopping their service, I´m looking for a similar service and found you. 
Unfortunately the export of the shapefile isn´t the same with lines, points and polygons in stead of _osm_roads & _osm_waterareas etc. 

Is there a way to implement this in the future?
![shapefileexport](https://user-images.githubusercontent.com/21360782/34512146-a907b3a2-f060-11e7-8146-718e8f407430.JPG)

**Comment by bdon** [comment]
This should be possible by creating a custom YAML feature selection with each osm_* as a theme. The Export Tool doesn't do any generalization (_gen0, _gen1) however. 

I'll work on an example YAML and post it here

**Comment by fcujorick** [comment]
Hi, 

Thank you that would be great, 
Maybe it's cool (now Mapzen stops) to implement the IMPOSM shapefile sorted by _osm_* like this in the future as well.

![example2](https://user-images.githubusercontent.com/21360782/34527307-75e3b06c-f0a5-11e7-8fc2-58722248d68f.JPG)

**Comment by bdon** [comment]
@fcujorick 

The IMPOSM shapefile specification is here: https://raw.githubusercontent.com/omniscale/imposm3/master/example-mapping.yml

Here's an example of an Export Tool YAML for the first 3 tables:

```
admin:
  types:
    - polygons
  select:
    - name
    - boundary
    - admin_level
  where:
    - boundary = 'administrative'
aeroways:
  types:
    - lines
  select:
    - name
    - aeroway
  where:
    - aeroway IN ('runway','taxiway')
amenities:
  types:
    - points
  select:
    - name
    - amenity
  where:
    - amenity in ('university','school','library','fuel','hospital','fire_station','police')
```

The translation from the Imposm format to the Export tool format is pretty straightforward, however:

* the Imposm format uses the special "mapping_value" to refer to the mapped key for that table e.g. administrative, aeroway, amenity
* the export tool yaml doesn't do any column renaming

Is that enough to get you started? I recommend first trying it out with only the subset of tables you need from the Imposm spec linked above, as it's several hundred lines long.
