### ISSUE TITLE
`healthcare` export category missing clinics

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/osm-export-tool#287]
Not sure if this is the right location to post this - but the `Healthcare` tags seem to miss clinics (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclinic)

```
planet_osm_point:
  types:
    - points
  select:
    - access
    - amenity
    - 'health_facility:bed'
    - 'health_facility:level'
    - 'health_facility:type'
    - healthcare
    - 'medical_system:western'
    - name
    - opening_hours
    - operator
    - shop
    - 'staff_count:doctors'
    - 'staff_count:nurses'
    - status
    - 'toilets:disposal'
    - 'toilets:handwashing'
  where:
    - 'healthcare IS NOT NULL OR amenity IN (''doctors'', ''dentist'', ''toilets'', ''hospital'', ''pharmacy'') OR shop IN (''herbalist'',''nutrition_supplements'')'
planet_osm_polygon:
  types:
    - polygons
  select:
    - access
    - amenity
    - 'health_facility:bed'
    - 'health_facility:level'
    - 'health_facility:type'
    - healthcare
    - 'medical_system:western'
    - name
    - opening_hours
    - operator
    - shop
    - 'staff_count:doctors'
    - 'staff_count:nurses'
    - status
    - 'toilets:disposal'
    - 'toilets:handwashing'
  where:
    - 'healthcare IS NOT NULL OR amenity IN (''doctors'', ''dentist'', ''toilets'', ''hospital'', ''pharmacy'') OR shop IN (''herbalist'',''nutrition_supplements'')'
```
