### ISSUE TITLE
Question about config (where predicate) and export (additional layers point and multipolygons)

### ISSUE THREAD

**Issue by sfkeller** [hotosm/osm-export-tool#308]
I have two questions/issues with the YAML config and the export layers generated (GeoPackage), given this YAML config.:

```
retail:
  types:
    - points
    - polygons
  select:
    - name
  where:
    - shop IS NOT NULL
    - amenity='marketplace' OR shop='supermarket'
```

Q1. Why is there an additionaly layer "..._points" and "_...multipolygons" generated in addition to layer "retail"?

Q2. The two lines at the "where" predicate obviously are "OR"ed, generating an SQL WHERE statement as follows "WHERE (shop IS NOT NULL) OR (amenity='marketplace' OR shop='supermarket')". Correct? Looking at help https://export.hotosm.org/en/v3/learn/yaml gives no clue about this.

BTW: The export format default should IMHO be GeoPackage (or none).
